appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: H7GvD/nbbR4cMo3kP+k7uPGfUBXekQ1gULP4bkiOxRHq8NqCw+8aq4gYG6/Yxees4nJN6P3tGTk0U/BshIDbVDCmQlHId4LYwBHbhuZkJnqgeSE9/ov2ip3jLQkYO0FCAJxynZSoUWU/vkZ/BJnlrXo1qc3xUH0+JQtq7bTTq7lj/aEKrv9JtIgvYuT61STXgZFJolCuoFMqJqGbpYDggSddOvREM/2q2HWsF9rIZzeXxzoHmEbjF9X8z6BJnxRZ6TRrYqkywCunDUuzNl8hVc3INmbU9iX5TwgELzahUDGq9MLAr0UMb9u90S8HihHiy7vj4a2jvGBXYi8h1s6jTrIsLJmoQEPdZNpq+sXONvcBqcKBhqN1omkaaM5SBo8rNuYPnErukv6OnR/Rk1dIOuM7etRMH35CX4h8yM+ln9pR83mne6jIEBcMMKG/wGrN2MA+X9O+VGPAHlWGx+B+ydzKmAHbGA1Xze/o8VMmK8wLkJGa8Qkc3/O80VB3iPNlOUggQIaMcnSf8Rykv+SQ0ft4osR2YXrbgg0/xvg5OpHHblU+vQCg2fR0O39Uucxf9//kh4nGiNr/4a1MlkpgOR6T13Y/PkO+VrcAtSvZyyF1x1NxfmefKOy0vWa3qsAjY2pcFTUKp23KGRZ0PnILBGawt5w7f2FE99yVpdy9dtw=}
